Update build-armbian.yml

diff --git a/.github/workflows/build-armbian.yml b/.github/workflows/build-armbian.yml
--- a/.github/workflows/build-armbian.yml
+++ b/.github/workflows/build-armbian.yml
@@ -1,29 +1,18 @@
-
 #==========================================================================
 # Description: Build Armbian For Amlogic s9xxx tv box
 # Copyright (C) 2021 https://github.com/ophub/amlogic-s9xxx-armbian
 #==========================================================================
 
-name: Build armbian
+name: Rebuild armbian
 
 on:
   repository_dispatch:
   workflow_dispatch:
     inputs:
-      set_release:
-        description: "RELEASE: focal / bullseye / buster"
-        required: false
-        default: "focal"
-      set_board:
-        description: "BOARD: lepotato / odroidn2"
-        required: false
-        default: "lepotato"
-      set_opts:
-        description: "More build options: for compile.sh"
+      armbian_url:
+        description: "Input armbian path"
         required: false
         default: ""
-  #schedule:
-    #- cron: "0 17 * * 0"
 
 env:
   TZ: Asia/Shanghai
@@ -49,53 +38,47 @@ jobs:
           sudo timedatectl set-timezone "$TZ"
           sudo mkdir -p /workdir
           sudo chown $USER:$GROUPS /workdir
+          # Get the url of the rebuild armbian file
+          armbian_url="${{ github.event.inputs.armbian_url }}"
+          if  [[ -z "${armbian_url}" ]]; then
+              armbian_site="https://armbian.tnahosting.net/dl/lepotato/archive/"
+              armbian_name="Armbian.*focal.*.img.xz"
+              armbian_file=$(curl -s "${armbian_site}" | grep -oE "${armbian_name}" | head -n 1)
+              if [ -n "${armbian_file}" ]; then
+                  armbian_url="${armbian_site}/${armbian_file}"
+              else
+                  echo -e "Invalid download path: [ ${armbian_site} ]"
+                  exit 1
+              fi
+          fi
+          echo "ARMBIAN_URL=${armbian_url}" >> $GITHUB_ENV
           echo "COMPILE_STARTINGTIME=$(date +"%Y.%m.%d.%H%M")" >> $GITHUB_ENV
-          ARR_RELEASE=("focal" "bullseye" "buster")
-          set_release="${{ github.event.inputs.set_release }}"
-          if  [[ -z "${set_release}" || -z "$(echo "${ARR_RELEASE[@]}" | grep -w "${set_release}")" ]]; then
-              set_release="focal"
-          fi
+          # Get the release name of the rebuild armbian file
+          set_release="_"
+          ARR_RELEASE=("bionic" "focal" "hirsute" "bullseye" "buster" "stretch")
+          i=1
+          for r in ${ARR_RELEASE[*]}; do
+              if [[ "${armbian_url}" == *${r}* ]]; then
+                  set_release="_${r}_"
+                  break
+              fi
+              let i++
+          done
           echo "ARMBIAN_RELEASE=${set_release}" >> $GITHUB_ENV
-          ARR_BOARD=("lepotato" "odroidn2")
-          set_board="${{ github.event.inputs.set_board }}"
-          if  [[ -z "${set_board}" || -z "$(echo "${ARR_BOARD[@]}" | grep -w "${set_board}")" ]]; then
-              set_board="lepotato"
-          fi
-          echo "ARMBIAN_BOARD=${set_board}" >> $GITHUB_ENV
-          echo "ARMBIAN_MORE_OPTS=${{ github.event.inputs.set_opts }}" >> $GITHUB_ENV
-      - name: Download source code
-        id: down
-        run: |
-          git clone --depth 1 https://github.com/armbian/build.git
-      - name: Compile Armbian [ ${{ env.ARMBIAN_BOARD }} ]
-        id: compile
-        run: |
-          cd build/
-          sudo chmod +x compile.sh
-          sudo ./compile.sh BOARD=${{ env.ARMBIAN_BOARD }} RELEASE=${{ env.ARMBIAN_RELEASE }} BRANCH=current \
-                            BUILD_MINIMAL=no BUILD_DESKTOP=no HOST=armbian KERNEL_ONLY=no KERNEL_CONFIGURE=no \
-                            CLEAN_LEVEL=make,debs COMPRESS_OUTPUTIMAGE=sha,img ${{ env.ARMBIAN_MORE_OPTS }}
-          echo "::set-output name=status::success"
-      - name: Rebuild Armbian for amlogic s9xxx
-        id: rebuild
-        if: steps.compile.outputs.status == 'success' && !cancelled()
-        run: |
-          sudo chmod +x rebuild
-          #sudo ./rebuild -d -b s905x3_s905x -k 5.4.170_5.10.90 -v dev
-          #sudo rm -rf build-armbian/amlogic-kernel/* && sync
-          sudo ./rebuild -d -b s922x_s922x-n2_s922x-reva_s905d_s912_s912-t95z_s905x2_s905_s905d-ki_s905x3_s905x -k 5.4.170_5.10.90
-          sudo ./rebuild -d -b s905w -k 5.4.170
-          cd build/output/images/ && sudo gzip *.img && sync
-          echo "FILEPATH=$PWD" >> $GITHUB_ENV
-          echo "FILE_DATE=$(date +"%Y.%m.%d.%H%M")" >> $GITHUB_ENV
-          echo "::set-output name=status::success"
+      - name: Rebuild Armbian for Amlogic s9xxx
+        uses: ophub/amlogic-s9xxx-armbian@main
+        with:
+          armbian_path: ${{ env.ARMBIAN_URL }}
+          armbian_soc: s905x3_s905d
+          armbian_kernel: 5.4.170_5.10.90_5.15.13_5.16.3
+
       - name: Upload Armbian image to Release
         id: release
         uses: ncipollo/release-action@v1
-        if: steps.rebuild.outputs.status == 'success' && !cancelled()
+        if: env.PACKAGED_STATUS == 'success' && !cancelled()
         with:
-          tag: Armbian_Aml_${{ env.ARMBIAN_RELEASE }}_${{ env.FILE_DATE }}
-          artifacts: ${{ env.FILEPATH }}/*
+          tag: Armbian_Aml${{ env.ARMBIAN_RELEASE }}${{ env.PACKAGED_OUTPUTDATE }}
+          artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
           allowUpdates: true
           token: ${{ secrets.GITHUB_TOKEN }}
           body: |
@@ -104,3 +87,5 @@ jobs:
             Default username: root
             Default password: 1234
             Install to EMMC command: armbian-install
+            Update command: armbian-update
+  
