Update compile-kernel.yml

diff --git a/.github/workflows/compile-kernel.yml b/.github/workflows/compile-kernel.yml
--- a/.github/workflows/compile-kernel.yml
+++ b/.github/workflows/compile-kernel.yml
@@ -9,14 +9,10 @@ on:
   repository_dispatch:
   workflow_dispatch:
     inputs:
-      kernel_repo:
-        description: "Source: kernel.org / unifreq"
+      armbian_url:
+        description: "Input armbian path"
         required: false
-        default: "unifreq"
-      kernel_version:
-        description: "Kernel version: 5.4.170"
-        required: false
-        default: "5.10.90_5.4.170_5.15.15_5.16.2"
+        default: ""
 
 env:
   TZ: Asia/Shanghai
@@ -40,24 +36,44 @@ jobs:
           sudo -E apt-get -qq autoremove --purge
           sudo -E apt-get -qq clean
           sudo timedatectl set-timezone "$TZ"
+          sudo mkdir -p /workdir
+          sudo chown $USER:$GROUPS /workdir
+          # Get the url of the rebuild armbian file
+          armbian_url="${{ github.event.inputs.armbian_url }}"
+          if  [[ -z "${armbian_url}" ]]; then
+              armbian_site="https://armbian.tnahosting.net/dl/lepotato/archive/"
+              armbian_name="Armbian.*focal.*.img.xz"
+              armbian_file=$(curl -s "${armbian_site}" | grep -oE "${armbian_name}" | head -n 1)
+              if [ -n "${armbian_file}" ]; then
+                  armbian_url="${armbian_site}/${armbian_file}"
+              else
+                  echo -e "Invalid download path: [ ${armbian_site} ]"
+                  exit 1
+              fi
+          fi
+          echo "ARMBIAN_URL=${armbian_url}" >> $GITHUB_ENV
           echo "COMPILE_STARTINGTIME=$(date +"%Y.%m.%d.%H%M")" >> $GITHUB_ENV
-          kernel_repo="${{ github.event.inputs.kernel_repo }}"
-          [ -z "${kernel_repo}"] && kernel_repo="kernel.org"
-          echo "KERNEL_REPO=${kernel_repo}" >> $GITHUB_ENV
-          kernel_version="${{ github.event.inputs.kernel_version }}"
-          [ -z "${kernel_version}" ] && kernel_version="5.10.90_5.4.170_5.15.15_5.16.2"
-          echo "KERNEL_VERSION=${kernel_version}" >> $GITHUB_ENV
+          # Get the release name of the rebuild armbian file
+          set_release="_"
+          ARR_RELEASE=("bionic" "focal" "hirsute" "bullseye" "buster" "stretch")
+          i=1
+          for r in ${ARR_RELEASE[*]}; do
+              if [[ "${armbian_url}" == *${r}* ]]; then
+                  set_release="_${r}_"
+                  break
+              fi
+              let i++
+          done
+          echo "ARMBIAN_RELEASE=${set_release}" >> $GITHUB_ENV
       - name: Compile the kernel for Amlogic s9xxx
-        id: compile
-        run: |
-          sudo chmod +x recompile
-          sudo ./recompile -d -k ${{ env.KERNEL_VERSION }} -r ${{ env.KERNEL_REPO }}
-          output_dirname="${PWD}/compile-kernel/output"
-          output_tags="$(ls ${output_dirname}/*.tar.gz -l | awk '{print $9}' | grep -oE '[1-9].[0-9]{1,3}.[0-9]+' | xargs | tr "[ ]" "_")"
-          echo "PACKAGED_OUTPUTTAGS=${output_tags}" >> $GITHUB_ENV
-          echo "PACKAGED_OUTPUTPATH=${output_dirname}" >> $GITHUB_ENV
-          echo "PACKAGED_OUTPUTDATE=$(date +"%Y.%m.%d.%H%M")" >> $GITHUB_ENV
-          echo "::set-output name=status::success"
+        uses: ophub/amlogic-s9xxx-armbian@main
+        with:
+          build_target: kernel
+          kernel_version: 5.15.13_5.4.170
+          kernel_auto: true
+          armbian_kernel: 5.4.170_5.10.90_5.15.12_5.16.2
+          kernel_sign: -BGG
+
       - name: Upload Kernel to Release
         uses: ncipollo/release-action@v1
         if: steps.compile.outputs.status == 'success' && !cancelled()
